spring:
  application:
    name: livestream-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/livestream}
    username: ${DB_USERNAME:stream}
    password: ${DB_PASSWORD:stream}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:livestream-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080
